# -*- coding: utf-8 -*-
"""someAnalysis.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12LsRRXf7cOaL1VJPcEH7uRGEM-P-6-mt
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

data_path = "probing_data.csv"
data = pd.read_csv(data_path,
                   names = ['pat_num','JJ_num','V_sam','V_err',"R_print","R_calc","Vmon","Rbias"],
                  skiprows=1)

my_dict = {"3B":[], "3C":[], "3F":[]}
for key in ["3B","3C","3F"]:
  my_dict[key] = data[data.pat_num==key].R_calc

support = np.linspace(300,950, 1000)
dr = 10
for key in my_dict.keys():
  resistances = my_dict[key]
  top_hat_density = [sum( abs(r-resistances)<dr ) for r in support ]
  smoothed = sum(  abs(support-r) <dr  for r in resistances )
  plt.plot(support, smoothed,'-',label=key)
plt.xlabel("Resistance [$\Omega$]")
plt.ylabel("Tophat Density Estimate [counts]")
plt.title("Column 3 resistances")
plt.legend(title="Group label")
plt.show()

